services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/pghosh/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    command: bash
    tty: true
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
